"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](bold bright-black) $os\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$fill$time 
[╰─](bold bright-black) $shell$character"""
# A minimal left prompt
# format = """$character"""
command_timeout = 3000
scan_timeout = 50
add_newline = true

[fill]
symbol = '─'
style = "bright-black"

[os]
disabled = false
style = "bold blue"

[os.symbols]
Windows = "󰖳 "
Arch = " "
Macos = " "

[shell]
disabled = false
powershell_indicator = ""
xonsh_indicator = "󰁥"
zsh_indicator = '❭'
style = "bold green"

[character]
success_symbol = "[](bold green)"
error_symbol = "[⛌ ](bold red)"

[directory]
use_os_path_sep = false
format = "[ $path]($style)[$read_only]($read_only_style) "
read_only = " 󰉐 "
style = "blue cyan"

[package]
symbol = "󰏖 "

[java]
symbol = "󰬷 "

[lua]
symbol = "󰢱 "

[time]
disabled = false
format = "[  $time ]($style)"
time_format = "%Y-%m-%d %T"
# style = "bg:yellow fg:black"
